import React, { useCallback, useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from "react-native";
import { CameraView, useCameraPermissions } from "expo-camera";
import { Camera, Flashlight, Focus, Minus, Plus, X, Zap } from "lucide-react-native";

export function BarcodeScanner({ color, onScan }: { color: string; onScan: (value: string) => void }) {
  const [permission, requestPermission] = useCameraPermissions();
  const [open, setOpen] = useState(false); const [scanned, setScanned] = useState(false);
  const [torch, setTorch] = useState(false); const [zoom, setZoom] = useState(0); const [focusLock, setFocusLock] = useState(false);
  const begin = async () => { if (!permission?.granted) { const result = await requestPermission(); if (!result.granted) return; } setScanned(false); setOpen(true); };
  const close = () => { setOpen(false); setTorch(false); setZoom(0); setFocusLock(false); };
  const refocus = useCallback(() => { setFocusLock(true); setTimeout(() => setFocusLock(false), 700); }, []);
  const adjustZoom = (amount: number) => setZoom((current) => Math.max(0, Math.min(0.75, Number((current + amount).toFixed(2)))));
  if (!open) return <Pressable onPress={begin} style={[styles.open, { backgroundColor: color }]}><Camera color="#fff" size={20}/><Text style={styles.openText}>Open scanner</Text></Pressable>;
  return <View style={styles.cameraWrap}><CameraView style={styles.camera} facing="back" autofocus={focusLock ? "on" : "off"} enableTorch={torch} zoom={zoom} barcodeScannerSettings={{ barcodeTypes: ["qr", "ean13", "ean8", "upc_a", "upc_e", "code128", "code39"] }} onBarcodeScanned={scanned ? undefined : ({ data }) => { setScanned(true); close(); onScan(data); }} />
    <View pointerEvents="none" style={styles.dimTop}/><View pointerEvents="none" style={styles.dimBottom}/><View pointerEvents="none" style={[styles.frame, { borderColor: color }]}/><View pointerEvents="none" style={styles.guide}><Text style={styles.guideText}>Align barcode inside the frame</Text></View>
    <Pressable accessibilityLabel="Close camera" onPress={close} style={styles.close}><X size={20} color="#101828"/></Pressable><View style={styles.tools}><Pressable accessibilityLabel="Zoom out" onPress={() => adjustZoom(-0.1)} style={styles.tool}><Minus size={19} color="#fff"/></Pressable><View style={styles.zoomReadout}><Text style={styles.zoomText}>{Math.round(1 + zoom * 4)}x</Text></View><Pressable accessibilityLabel="Zoom in" onPress={() => adjustZoom(0.1)} style={styles.tool}><Plus size={19} color="#fff"/></Pressable><Pressable accessibilityLabel="Refocus camera" onPress={refocus} style={[styles.tool, focusLock && { backgroundColor: color }]}><Focus size={19} color="#fff"/></Pressable><Pressable accessibilityLabel="Toggle torch" onPress={() => setTorch((value) => !value)} style={[styles.tool, torch && { backgroundColor: "#f59e0b" }]}>{torch ? <Zap size={19} color="#fff" fill="#fff"/> : <Flashlight size={19} color="#fff"/>}</Pressable></View><Text style={styles.tip}>Use + for small labels. Tap focus after moving closer.</Text>{scanned && <ActivityIndicator color="#fff" size="large" style={styles.loading}/>}</View>;
}
const styles = StyleSheet.create({ open:{height:52,borderRadius:14,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:9,shadowColor:"#101828",shadowOpacity:.16,shadowRadius:10,elevation:3},openText:{color:"#fff",fontWeight:"800",fontSize:15},cameraWrap:{height:330,borderRadius:18,overflow:"hidden",backgroundColor:"#101828"},camera:{flex:1},dimTop:{position:"absolute",top:0,left:0,right:0,height:"25%",backgroundColor:"#00000045"},dimBottom:{position:"absolute",bottom:0,left:0,right:0,height:"32%",backgroundColor:"#00000055"},frame:{position:"absolute",left:"8%",right:"8%",top:"30%",height:"31%",borderWidth:2,borderRadius:12,backgroundColor:"#ffffff08"},guide:{position:"absolute",left:0,right:0,top:"63%",alignItems:"center"},guideText:{color:"#fff",fontWeight:"700",fontSize:12,textShadowColor:"#000",textShadowRadius:4},close:{position:"absolute",right:12,top:12,width:38,height:38,borderRadius:19,backgroundColor:"#fff",alignItems:"center",justifyContent:"center"},tools:{position:"absolute",bottom:43,left:12,right:12,flexDirection:"row",justifyContent:"center",gap:8},tool:{height:42,width:42,borderRadius:21,backgroundColor:"#101828cc",alignItems:"center",justifyContent:"center",borderWidth:1,borderColor:"#ffffff35"},zoomReadout:{minWidth:44,height:42,borderRadius:21,backgroundColor:"#101828cc",alignItems:"center",justifyContent:"center",borderWidth:1,borderColor:"#ffffff35"},zoomText:{color:"#fff",fontWeight:"800",fontSize:13},tip:{position:"absolute",bottom:12,left:16,right:16,color:"#fff",fontSize:11,textAlign:"center",fontWeight:"600"},loading:{position:"absolute",alignSelf:"center",top:"45%"} });
